TARGET_ARCH = linux
# build with: i386-pc-linux, but compile with lib-linux

CC = g++
OPT    = -O3 
DEBUG  =    
CFLAGS = $(DEBUG) $(OPT) -fexceptions

MODULE = run
SRCS = immediateEvent.cpp
OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs
