#ifndef _FIND_SCMAIN_H_
#define _FIND_SCMAIN_H_

#include "clang/AST/RecursiveASTVisitor.h"

// Forward declarations
// Generated by iwyu
//
namespace clang { class FunctionDecl; }
namespace clang { class TranslationUnitDecl; }
namespace llvm { class raw_ostream; }

using namespace clang;
namespace scpar {

class FindSCMain : public RecursiveASTVisitor<FindSCMain> {
public:
  FindSCMain(TranslationUnitDecl *, llvm::raw_ostream &);
  virtual ~FindSCMain();
  virtual bool VisitFunctionDecl(FunctionDecl *decl);

  FunctionDecl *getSCMainFunctionDecl() const;
  bool isSCMainFound() const;

private:
  llvm::raw_ostream &os_;
  FunctionDecl *sc_main_function_declaration_;
};
} // namespace scpar
#endif
